  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#  instance:
#    hostname: clientName
server:
  port: 8762
spring:
  application:
    name: client 
# env 就是环境的意思
env: 
  dev
